### ISSUE TITLE
ComboTrackSelector fails in JBrowse-1.14.0-dev and above

### ISSUE THREAD

**Issue by vaneet-lotay** [Arabidopsis-Information-Portal/ComboTrackSelector#2]
When trying to load the plugin it fails to display properly in the hierarchical track selector pane.  See my screenshot below of my test space in JBrowse where I test this plugin.  The plugin seems to function ok, in terms of the faceted button going to the faceted track selector succesfully and loading the metadata correctly but when the button is drawn it is blocking part of the main tracklist pane.

Can you fix this please?  This issue wasn't present for JBrowse-1.13-1-dev.

Thanks,

Vaneet

![faceted_screenshot](https://user-images.githubusercontent.com/40072920/41181070-bc35b486-6b2d-11e8-8a52-fcdcafe62d5d.png)

**Comment by vivekkrish** [comment]
Hi @vaneet-lotay, a minor fix #3 was recently merged to the main branch. Could you please test this latest version to see if it resolves the rendering issue? Thanks!

**Comment by vaneet-lotay** [comment]
Thanks Vivek. I saw the fix and will try it with the latest JBrowse upgrade. Will let you know how it goes.

Vaneet



On Jun 15, 2018 7:01 PM, Vivek Krishnakumar <notifications@github.com> wrote:

Hi @vaneet-lotay<https://github.com/vaneet-lotay>, a minor fix #3<https://github.com/Arabidopsis-Information-Portal/ComboTrackSelector/pull/3> was recently merged to the main branch. Could you please test this latest version to see if it resolves the rendering issue? Thanks!

**Comment by vaneet-lotay** [comment]
Hey Vivek,

I pulled the latest release of the code for this plugin and tried it while upgrading to JBrowse-1.14.2-dev (latest release) after running all the setup scripts but it still has the same issues:

![image](https://user-images.githubusercontent.com/40072920/41688296-cf5c566c-74a8-11e8-8b48-dd280da37cf5.png)

The text font in the Faceted Track Selector button as well as the pop-up table looks correct.  The text of 'Tracks Available in Faceted List' has shifted more to the background so I can see that some changes have taken place but the button and text are still overlaying on top of the tracklist pane blocking the track names to be selected.

Maybe something changed from JBrowse-1.14-0-dev to JBrowse-1.14-2.dev in case you had it working with the previous releases?

Please let me know if you can fix it.

Thanks,

Vaneet

**Comment by vaneet-lotay** [comment]
Hey Vivek,

If you happen to be posting a fix to the code could you also make sure the font case that the facet columns are shown match the way they are displayed in the table columns. That is if one display column is capitalized in the table it would be nice if it's also capitalized when it's showing the facets on the left panel:

![cts_faceted_caps_issue](https://user-images.githubusercontent.com/40072920/41747481-62d25596-756b-11e8-9ef2-d1b329ea1b55.png)

I'm not sure if this is something you can possibly fix or should I should bring it to the main JBrowse developers.

Thanks,

Vaneet

**Comment by vaneet-lotay** [comment]
Hey Vivek,

Is there any chance there will be another fix put out for this re-occuring issue with the ComboTrackSelector plugin?  I'm asking because we were really hoping to use if for a big project we're working on at Xenbase that involves hundreds of new JBrowse tracks.  The use of the plugin would be beneficial to navigate through the track names and their metadata.

Thanks,

Vaneet

**Comment by vaneet-lotay** [comment]
I've verified that this issue is fixed by testing it in the latest JBrowse v 1.16.3, thanks!

**Comment by vivekkrish** [comment]
Thanks for the update, @vaneet-lotay 

CC @agnespychan, @ywchoi, @cdtown
